//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Agent
    {
        public int int_AGid { get; set; }
        public string vchar_AGcode { get; set; }
        public string vchar_AGname { get; set; }
        public string vchar_AGLinkMan { get; set; }
        public string vchar_AGcontect { get; set; }
        public short int_AGtype { get; set; }
        public bool bit_synOpen { get; set; }
        public string vchar_synVerify { get; set; }
        public string vchar_synStopKeyWord { get; set; }
        public Nullable<int> int_synSpacing { get; set; }
        public bool bit_synQuery { get; set; }
        public string vchar_QueryVerify { get; set; }
        public bool bit_synPush { get; set; }
        public string vchar_PushUser { get; set; }
        public string vchar_PushVerify { get; set; }
        public bool IsOpen { get; set; }
    }
}
