//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SFI_TrackNum
    {
        public int int_Mappingid { get; set; }
        public string vchar_SFInum { get; set; }
        public string vchar_AGnum { get; set; }
        public int int_AGid { get; set; }
        public string vchar_updateUser { get; set; }
        public Nullable<System.DateTime> dttm_updateDttm { get; set; }
        public Nullable<System.DateTime> dttm_AG_LastSyn { get; set; }
        public short int_AG_Syn { get; set; }
        public string char_IsStop { get; set; }
        public string char_AG_Syn_sign { get; set; }
    }
}
