//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace SyncOrderTracking.ru.dpd.wstest {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ParcelTracingPortBinding", Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class ParcelTracingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getStatesByClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatesByClientOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatesByClientParcelOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatesByDPDOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback confirmOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ParcelTracingService() {
            this.Url = global::SyncOrderTracking.Properties.Settings.Default.SyncOrderTracking_ru_dpd_wstest_ParcelTracingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getStatesByClientCompletedEventHandler getStatesByClientCompleted;
        
        /// <remarks/>
        public event getStatesByClientOrderCompletedEventHandler getStatesByClientOrderCompleted;
        
        /// <remarks/>
        public event getStatesByClientParcelCompletedEventHandler getStatesByClientParcelCompleted;
        
        /// <remarks/>
        public event getStatesByDPDOrderCompletedEventHandler getStatesByDPDOrderCompleted;
        
        /// <remarks/>
        public event confirmCompletedEventHandler confirmCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://dpd.ru/ws/tracing/2011-11-18", ResponseNamespace="http://dpd.ru/ws/tracing/2011-11-18", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stateParcels getStatesByClient([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] requestClient request) {
            object[] results = this.Invoke("getStatesByClient", new object[] {
                        request});
            return ((stateParcels)(results[0]));
        }
        
        /// <remarks/>
        public void getStatesByClientAsync(requestClient request) {
            this.getStatesByClientAsync(request, null);
        }
        
        /// <remarks/>
        public void getStatesByClientAsync(requestClient request, object userState) {
            if ((this.getStatesByClientOperationCompleted == null)) {
                this.getStatesByClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatesByClientOperationCompleted);
            }
            this.InvokeAsync("getStatesByClient", new object[] {
                        request}, this.getStatesByClientOperationCompleted, userState);
        }
        
        private void OngetStatesByClientOperationCompleted(object arg) {
            if ((this.getStatesByClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatesByClientCompleted(this, new getStatesByClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://dpd.ru/ws/tracing/2011-11-18", ResponseNamespace="http://dpd.ru/ws/tracing/2011-11-18", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stateParcels getStatesByClientOrder([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] requestClientOrder request) {
            object[] results = this.Invoke("getStatesByClientOrder", new object[] {
                        request});
            return ((stateParcels)(results[0]));
        }
        
        /// <remarks/>
        public void getStatesByClientOrderAsync(requestClientOrder request) {
            this.getStatesByClientOrderAsync(request, null);
        }
        
        /// <remarks/>
        public void getStatesByClientOrderAsync(requestClientOrder request, object userState) {
            if ((this.getStatesByClientOrderOperationCompleted == null)) {
                this.getStatesByClientOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatesByClientOrderOperationCompleted);
            }
            this.InvokeAsync("getStatesByClientOrder", new object[] {
                        request}, this.getStatesByClientOrderOperationCompleted, userState);
        }
        
        private void OngetStatesByClientOrderOperationCompleted(object arg) {
            if ((this.getStatesByClientOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatesByClientOrderCompleted(this, new getStatesByClientOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://dpd.ru/ws/tracing/2011-11-18", ResponseNamespace="http://dpd.ru/ws/tracing/2011-11-18", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stateParcels getStatesByClientParcel([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] requestClientParcel request) {
            object[] results = this.Invoke("getStatesByClientParcel", new object[] {
                        request});
            return ((stateParcels)(results[0]));
        }
        
        /// <remarks/>
        public void getStatesByClientParcelAsync(requestClientParcel request) {
            this.getStatesByClientParcelAsync(request, null);
        }
        
        /// <remarks/>
        public void getStatesByClientParcelAsync(requestClientParcel request, object userState) {
            if ((this.getStatesByClientParcelOperationCompleted == null)) {
                this.getStatesByClientParcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatesByClientParcelOperationCompleted);
            }
            this.InvokeAsync("getStatesByClientParcel", new object[] {
                        request}, this.getStatesByClientParcelOperationCompleted, userState);
        }
        
        private void OngetStatesByClientParcelOperationCompleted(object arg) {
            if ((this.getStatesByClientParcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatesByClientParcelCompleted(this, new getStatesByClientParcelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://dpd.ru/ws/tracing/2011-11-18", ResponseNamespace="http://dpd.ru/ws/tracing/2011-11-18", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stateParcels getStatesByDPDOrder([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] requestDpdOrder request) {
            object[] results = this.Invoke("getStatesByDPDOrder", new object[] {
                        request});
            return ((stateParcels)(results[0]));
        }
        
        /// <remarks/>
        public void getStatesByDPDOrderAsync(requestDpdOrder request) {
            this.getStatesByDPDOrderAsync(request, null);
        }
        
        /// <remarks/>
        public void getStatesByDPDOrderAsync(requestDpdOrder request, object userState) {
            if ((this.getStatesByDPDOrderOperationCompleted == null)) {
                this.getStatesByDPDOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatesByDPDOrderOperationCompleted);
            }
            this.InvokeAsync("getStatesByDPDOrder", new object[] {
                        request}, this.getStatesByDPDOrderOperationCompleted, userState);
        }
        
        private void OngetStatesByDPDOrderOperationCompleted(object arg) {
            if ((this.getStatesByDPDOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatesByDPDOrderCompleted(this, new getStatesByDPDOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://dpd.ru/ws/tracing/2011-11-18", ResponseNamespace="http://dpd.ru/ws/tracing/2011-11-18", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void confirm([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] requestConfirm request) {
            this.Invoke("confirm", new object[] {
                        request});
        }
        
        /// <remarks/>
        public void confirmAsync(requestConfirm request) {
            this.confirmAsync(request, null);
        }
        
        /// <remarks/>
        public void confirmAsync(requestConfirm request, object userState) {
            if ((this.confirmOperationCompleted == null)) {
                this.confirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmOperationCompleted);
            }
            this.InvokeAsync("confirm", new object[] {
                        request}, this.confirmOperationCompleted, userState);
        }
        
        private void OnconfirmOperationCompleted(object arg) {
            if ((this.confirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.confirmCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestClient {
        
        private auth authField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class auth {
        
        private long clientNumberField;
        
        private string clientKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long clientNumber {
            get {
                return this.clientNumberField;
            }
            set {
                this.clientNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientKey {
            get {
                return this.clientKeyField;
            }
            set {
                this.clientKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestConfirm {
        
        private auth authField;
        
        private long docIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestDpdOrder {
        
        private auth authField;
        
        private string dpdOrderNrField;
        
        private int pickupYearField;
        
        private bool pickupYearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dpdOrderNr {
            get {
                return this.dpdOrderNrField;
            }
            set {
                this.dpdOrderNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pickupYear {
            get {
                return this.pickupYearField;
            }
            set {
                this.pickupYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pickupYearSpecified {
            get {
                return this.pickupYearFieldSpecified;
            }
            set {
                this.pickupYearFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestClientParcel {
        
        private auth authField;
        
        private string clientParcelNrField;
        
        private System.DateTime pickupDateField;
        
        private bool pickupDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientParcelNr {
            get {
                return this.clientParcelNrField;
            }
            set {
                this.clientParcelNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime pickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pickupDateSpecified {
            get {
                return this.pickupDateFieldSpecified;
            }
            set {
                this.pickupDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class requestClientOrder {
        
        private auth authField;
        
        private string clientOrderNrField;
        
        private System.DateTime pickupDateField;
        
        private bool pickupDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public auth auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientOrderNr {
            get {
                return this.clientOrderNrField;
            }
            set {
                this.clientOrderNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime pickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pickupDateSpecified {
            get {
                return this.pickupDateFieldSpecified;
            }
            set {
                this.pickupDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class stateParcel {
        
        private string clientOrderNrField;
        
        private string clientParcelNrField;
        
        private string dpdOrderNrField;
        
        private string dpdParcelNrField;
        
        private System.DateTime pickupDateField;
        
        private string dpdOrderReNrField;
        
        private string dpdParcelReNrField;
        
        private bool isReturnField;
        
        private bool isReturnFieldSpecified;
        
        private System.DateTime planDeliveryDateField;
        
        private bool planDeliveryDateFieldSpecified;
        
        private string newStateField;
        
        private System.DateTime transitionTimeField;
        
        private string terminalCodeField;
        
        private string terminalCityField;
        
        private string incidentCodeField;
        
        private string incidentNameField;
        
        private string consigneeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientOrderNr {
            get {
                return this.clientOrderNrField;
            }
            set {
                this.clientOrderNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientParcelNr {
            get {
                return this.clientParcelNrField;
            }
            set {
                this.clientParcelNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dpdOrderNr {
            get {
                return this.dpdOrderNrField;
            }
            set {
                this.dpdOrderNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dpdParcelNr {
            get {
                return this.dpdParcelNrField;
            }
            set {
                this.dpdParcelNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime pickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dpdOrderReNr {
            get {
                return this.dpdOrderReNrField;
            }
            set {
                this.dpdOrderReNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dpdParcelReNr {
            get {
                return this.dpdParcelReNrField;
            }
            set {
                this.dpdParcelReNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isReturn {
            get {
                return this.isReturnField;
            }
            set {
                this.isReturnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isReturnSpecified {
            get {
                return this.isReturnFieldSpecified;
            }
            set {
                this.isReturnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime planDeliveryDate {
            get {
                return this.planDeliveryDateField;
            }
            set {
                this.planDeliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool planDeliveryDateSpecified {
            get {
                return this.planDeliveryDateFieldSpecified;
            }
            set {
                this.planDeliveryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newState {
            get {
                return this.newStateField;
            }
            set {
                this.newStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime transitionTime {
            get {
                return this.transitionTimeField;
            }
            set {
                this.transitionTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminalCode {
            get {
                return this.terminalCodeField;
            }
            set {
                this.terminalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminalCity {
            get {
                return this.terminalCityField;
            }
            set {
                this.terminalCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string incidentCode {
            get {
                return this.incidentCodeField;
            }
            set {
                this.incidentCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string incidentName {
            get {
                return this.incidentNameField;
            }
            set {
                this.incidentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consignee {
            get {
                return this.consigneeField;
            }
            set {
                this.consigneeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dpd.ru/ws/tracing/2011-11-18")]
    public partial class stateParcels {
        
        private long docIdField;
        
        private System.DateTime docDateField;
        
        private long clientNumberField;
        
        private bool resultCompleteField;
        
        private stateParcel[] statesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long docId {
            get {
                return this.docIdField;
            }
            set {
                this.docIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime docDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long clientNumber {
            get {
                return this.clientNumberField;
            }
            set {
                this.clientNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool resultComplete {
            get {
                return this.resultCompleteField;
            }
            set {
                this.resultCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("states", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stateParcel[] states {
            get {
                return this.statesField;
            }
            set {
                this.statesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getStatesByClientCompletedEventHandler(object sender, getStatesByClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatesByClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatesByClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stateParcels Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stateParcels)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getStatesByClientOrderCompletedEventHandler(object sender, getStatesByClientOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatesByClientOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatesByClientOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stateParcels Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stateParcels)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getStatesByClientParcelCompletedEventHandler(object sender, getStatesByClientParcelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatesByClientParcelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatesByClientParcelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stateParcels Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stateParcels)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getStatesByDPDOrderCompletedEventHandler(object sender, getStatesByDPDOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatesByDPDOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatesByDPDOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stateParcels Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stateParcels)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void confirmCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591